[package]
name = "ngit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
chrono = "0.4.24"
clap = "4.0.32"
flate2 = "1.0.25"
hex = "0.4.2"
sha-1 = "0.9.1"
