.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nss 1  "nss 0.0.1" 
.SH NAME
nss \- 
        This is Original Version Management System.
Learn git and rust for good developer.
.SH SYNOPSIS
\fBnss\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
.PP
        This is Original Version Management System.
Learn git and rust for good developer.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.SH SUBCOMMANDS
.TP
nss\-hash\-object(1)
Calclate object hash or Create object
.TP
nss\-cat\-file(1)
View object content
.TP
nss\-ls\-files(1)
Read index and view tracked files
.TP
nss\-update\-index(1)
Register file contents in the working diretory to the index
.TP
nss\-init(1)
Create your current dirctory into nss repository
.TP
nss\-manual(1)
Display manual
.TP
nss\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.0.1
.SH AUTHORS
Noshishi. <noshishi@noshishi.com>
